### ISSUE TITLE
Updating retrieval of local variable information from r2

### ISSUE THREAD

**Issue by chinmaydd** [radare/r2pipe.rs#17]
r2 now uses `afvb` for local variable information instead of `afaj`(as was the case when the library was implemented).

For easier parsing, we can use the `afvbj @ _addr_` for which the example output is as follows:
`[{"name":"local_8h","kind":"var","type":"int","ref":{"base":"rbp", "offset":-8}}]`

Considering this, it would be apt to update the `LVarInfo` struct to parse the reference better. A possible idea would be:

```rust
pub struct LVarRef {
    pub base: Option<String>,
    pub offset: Option<String>,
}
```

We would also need to update the `locals_of` function which fetches this information. 

Thoughts ?

**Comment by radare** [comment]
I think that all this functionality should be outside the core r2pipe module. The r2pipe api should support more transports and have better tests. All the high level logic of r2 commands providing a userfriendly api on top of them should be moved somewhere else imho

**Comment by sushant94** [comment]
I think it should remain here. I'm sure most people would prefer to use the rust structs that we provide as comapred to raw json parsing that they'll have to implement all over again. Besides, they can always use the raw form if they want to. It's not like we're making that harder to use in any way.

**Comment by radare** [comment]
Its great to see you again :) prehappy new year

**Comment by sushant94** [comment]
Great to be back!
Thanks, Happy new year to you too :)
