### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [radare/r2pipe.rs#19]
We were hoping to drop the rustc-serialize dependency in https://github.com/resetnow/xtensa2arm/issues/1 because [it is deprecated](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay), but can't because of this library. Any plans to replace rustc-serialize with a different library?

**Comment by radare** [comment]
Not for me, but makes sense to reduce or drop dependencies. Any suggestion? Feel free to send a pr if you have any proposal/patch

**Comment by dtolnay** [comment]
For JSON I would definitely recommend Serde. Is it being used for anything else?

**Comment by radare** [comment]
R2pipe.rs is used by radeco and rune iirc but you can break them if its for good

**Comment by jrozner** [comment]
Just submitted a pull request that does this. Take a look at #20

**Comment by radare** [comment]
it was merged

**Comment by jrozner** [comment]
This needs to be manually closed because I didn't add one of the keywords into the commit message unfortunately.
