### ISSUE TITLE
r2p.cmd() should trim()?

### ISSUE THREAD

**Issue by radare** [radare/r2pipe.rs#4]

**Comment by radare** [comment]
yup it should, as long as we do the same in the python, node and c# bindings

**Comment by sushant94** [comment]
What's the intention of trim()? Since the returned values are `String`, users may choose to run `trim()` on the same. Maybe I misunderstand this issue.

**Comment by radare** [comment]
the problem is that commands sent to the r2pipe endpoint must not contain non-printable chars. mainly because \n can be intepreted as ;, but replying in 2 different responses.which breaks the r2pipe workflow. you can find PoCs for this bug in r2b. also, many ppl use the output of commands as input for another commands. so trimming the output also helps to avoid this situation.

in fact, there’s no sense to run commands with newlines or spaces at the begining or end of the string. So we can fix this with trim. but if those chars are in the middle. the api should fail without sending the command
